version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      #      - MYSQL_USER=application
      #      - MYSQL_PASSWORD=application
      MYSQL_DATABASE: hhplus
    volumes:
      #      - ./data/mysql/:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  default:
    driver: bridge